### ISSUE TITLE
eslint-plugin-jsx-a11y 의존성 중복

### ISSUE THREAD

**Issue by shinwonse** [hyunmindev/nextjs-boilerplate#1]
안녕하세요! eslint 설정을 보다가 궁금한 점이 생겨 이슈 남깁니다.

airbnb 플러그인을 extends  중이신 상태에서, jsx-a11y 플러그인을 추가로 설치하신 이유가 무엇인가요?
[eslint-config-airbnb](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json)을 보면 이미 jsx-a11y가 설치돼있는 것으로 보여서요.

**Comment by shinwonse** [comment]
해결했습니다. peer dependency 때문이군요

**Comment by hyunmindev** [comment]
@shinwonse 안녕하세요 원세님. 좋은 질문 감사합니다.
ESLint로 얘기 나눴을 때의 기억이 새록새록 하네요. 😊

말씀하신 대로 `eslint-config-arirbnb`는 이미 의존성으로 `jsx-a11y`를 갖고 있습니다.
따라서 다시 `jsx-a11y`를 다시 의존성으로 갖는다면, '추가로 설치하는 것'이라는 의문을 가질 수 있습니다.

짧은 답변:
`eslint-config-arirbnb`의 `jsx-a11y` 규칙은 `plugin:jsx-a11y/recommended` 보다 엄격하지 않습니다. 따라서 저의 의도는 `plugin:jsx-a11y/recommended`를 사용하는 것이고, 설치하지 않은 패키지를 사용하는 것은 혼동의 여지가 있다고 판단해서 직접 설치했습니다.

긴 답변:
`A` 패키지에서 `B` 패키지를 의존성으로 갖고, `C` 패키지에서 `B` 패키지를 의존성으로 갖는다고 가정해 보겠습니다. 이때 npm으로 `A`, `C` 패키지를 설치하면 중복되는 `B`는 (버전 충돌이 없으면) 의존성 트리의 상단으로 **호이스팅** 되어 한 번만 설치됩니다. 따라서 설치하지도 않은 `B` 패키지를 사용할 수 있는 이상한 상황이 생기는 겁니다. 이것을 **유령 의존성**이라고 부릅니다.
(물론 이를 방지하는 `import/no-extraneous-dependencies` 규칙도 있습니다.)

여기서 `B`에 해당하는 패키지가 `jsx-a11y` 입니다. 현재 의존성 구조상 호이스팅 되어 따로 설치 하지 않아도 사용할 수 있는 상태이죠. 설치 하지 않아도 사용할 수 있다는 점은 큰 혼란을 주는 것 같습니다. 마치 설치하지 않아도 되는 패키지를 중복으로 설치한다는 느낌까지 들고 말이죠. 이러한 부작용은 npm을 버리고 yarn berry를 채택하는 이유기도 합니다. 한 가지 확실한 것은 npm을 사용한다면 이러한 유령 의존성을 경계해야 한다는 것입니다.

**Comment by shinwonse** [comment]
@hyunmindev 친절한 답변 감사합니다. 긴 답변에서 새로운 의문점이 생기는데 만약 `B` 패키지가 버전 충돌이 있다면 호이스팅은 일어나지 않나요? 

제가 요새 회사 프론트엔드 코드의 eslint 설정을 패키지화하고 있는데, 여러 고민 사항이 있습니다. 혹시 내일 오후쯤에 온라인 미팅이 가능하실지요. 그리고 타 메신저에서 언급해주셨던 `beer time`은 다음주 토요일이 어떠신지 여쭙습니다.
